### ISSUE TITLE
AppImage on Linux is missing dependency

### ISSUE THREAD

**Issue by andrepasteur** [outscale/osc-cli#189]
Hello,

On Ubuntu 20.04, the AppImage version 1.8.0 is missing a dependency:

```
$ ./osc-cli-x86_64.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_osc-cl5brAGk/opt/python3.9/bin/osc-cli", line 34, in <module>
    sys.exit(load_entry_point('osc-sdk==1.8.0', 'console_scripts', 'osc-cli')())
  File "/tmp/.mount_osc-cl5brAGk/opt/python3.9/bin/osc-cli", line 26, in importlib_load_entry_point
    return next(matches).load()
  File "/tmp/.mount_osc-cl5brAGk/opt/python3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/tmp/.mount_osc-cl5brAGk/opt/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/.mount_osc-cl5brAGk/opt/python3.9/lib/python3.9/site-packages/osc_sdk-1.8.0-py3.9.egg/osc_sdk/__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/.mount_osc-cl5brAGk/opt/python3.9/lib/python3.9/site-packages/osc_sdk-1.8.0-py3.9.egg/osc_sdk/sdk.py", line 18, in <module>
ModuleNotFoundError: No module named 'typing_extensions' 
```

**Comment by jerome-jutteau** [comment]
Thanks André, we will check that
