### ISSUE TITLE
Manage 400 errors

### ISSUE THREAD

**Issue by jerome-jutteau** [outscale/osc-cli#294]
Hi,

Currently, if osc-cli get a 400, it will print a backtrace which is not quite a good user experience.

```bash
osc-cli api ReadVmsHealth --profile 'read-only' --LoadBalancerName 'XXX'
Traceback (most recent call last):
File "/var/lib/XXX/.venv/bin/osc-cli", line 11, in <module>
sys.exit(main())
File "/var/lib/XXX/.venv/lib64/python3.6/site-packages/osc_sdk/sdk.py", line 785, in main
fire.Fire(api_connect)
File "/var/lib/XXX/.venv/lib64/python3.6/site-packages/fire/core.py", line 141, in Fire
component_trace = _Fire(component, args, parsed_flag_args, context, name)
File "/var/lib/XXX/.venv/lib64/python3.6/site-packages/fire/core.py", line 480, in _Fire
target=component.__name__)
File "/var/lib/XXX/.venv/lib64/python3.6/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
component = fn(*varargs, **kwargs)
File "/var/lib/XXX/.venv/lib64/python3.6/site-packages/osc_sdk/sdk.py", line 766, in api_connect
handler.make_request(call, **kwargs)
File "/var/lib/XXX/.venv/lib64/python3.6/site-packages/osc_sdk/sdk.py", line 571, in make_request
verify=self.ssl_verify,
File "/var/lib/XXX/.venv/lib64/python3.6/site-packages/osc_sdk/sdk.py", line 502, in get_response
raise OscApiException(http_response)
osc_sdk.sdk.OscApiException: Error --> status = 400, code = 5063, code_type = InvalidResource, Reason = The VmId '{id}' doesn't exist., request_id = XXX
```

osc-cli should at least always catch exceptions and show a nice message when used as a cli (not a sdk)

**Comment by outscale-mgo** [comment]
Thanks for the issues, but this project is in maintenance mode, new CLI features should be done on [oapi-cli](https://github.com/outscale/oapi-cli)
If you really want that, you can still make a Pull Request.
